[tool.poetry]
name = "poetry-latoken"
version = "0.1.0"
description = ""
authors = ["vlad <vlad.genyuk@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
